baseURL = "https://chronicle.milzusvius.host/"
languageCode = "en-us"
title = "Milzusvius Chronicle"
theme = "hyde"

[params]
  description = " "
  copyright = " "

[taxonomies]
  appearances = "appearances"